## 1 对象
可用用来表示数据库的数据表之间的关系。


@startuml
object firstObject
object "My Second Object" as o2
@enduml

## 2 与类图中的通用特性
* 可见性
* 定义注释
* 使用包
* 美化输出内容
* 对象间关系

## 3 添加属性
* 
@startuml

object user

user : name = "Dummy"
user : id = 123

object user2 {
  name = "Dummy"
  id = 123
}
@enduml